homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirmation/', views.confirmation, name='confirmation')
]   

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls'))
]

homepage/models.py
from django.db import models
import datetime

# Create your models here.

class Status(models.Model):
    name = models.CharField(max_length = 255)
    status = models.CharField(max_length = 255)
    post_date = models.DateTimeField(auto_now_add=True)

homepage/forms.py
from django import forms
from .models import *

class UserInput(forms.Form):
    name = forms.CharField(label = 'Name', widget = forms.TextInput(), max_length=30)
    status = forms.CharField(label = 'Status', widget = forms.TextInput())

homepage/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.
def index(request):
    statusList = Status.objects.all()
    statusForm = UserInput()
    formInput = UserInput(request.POST)
    
    if request.method == 'GET':
        return render(request, 'index.html', {'statusList' : statusList, 'statusForm': statusForm})

    if request.method == 'POST':
        if formInput.is_valid():
            input = Status(name = formInput.data['name'], status = formInput.data['status'])
            input.save()
            return render(request, 'index.html', {'statusList' : statusList, 'statusForm': statusForm})
        else:
            return render(request, 'index.html', {'statusList' : statusList, 'statusForm': statusForm})


def confirmation(request):
    if request.method == 'POST':
        formInput = UserInput(request.POST)
        if formInput.is_valid():
            confirmName = formInput.data['name']
            confirmStatus = formInput.data['status']
            confirmForm = UserInput(initial={'name':confirmName, 'status':confirmStatus})
            return render(request, 'confirmation.html', {'confirmForm' : confirmForm})
        else:
            response = redirect('/')
            return response
    if request.method == 'GET':
        return redirect('/')

homepage/templates/confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset = "UTF-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
    <title>Story 7 Confirmation</title>
    <!-- Bootstrap CSS -->
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">
<style>
body{
background-color: gray;
}
</style>
</head>
<body>

    <form action="{% url 'homepage:index' %}" method="POST" style="text-align: center">
            {% csrf_token %}
            {{ confirmForm }}
            <p>Is the content of your message correct?</p>
            <input type="submit" name="yes" value="YES" >
        </form>
        <div style="text-align:center">
        <button type="submit" name="back" onclick="javascript:history.back()" id="id_no">NO</button>
        </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset = "UTF-8">
    <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
    <title>Story 7 Status</title>
    <!-- Bootstrap CSS -->
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/bootstrap.min.css' %}">
	<link rel = "stylesheet" type = "text/css" href = "{% static 'css/index.css' %}">
<style>
body{
background-color: gray;
}
</style>
</head>
<body>
    <br><br>
    <h1 style="text-align:center">What's on your mind today?</h1>
    <form class="m-5" method="POST" action="{% url 'homepage:confirmation' %}" style="text-align: center">
        {% csrf_token %}
        {{ statusForm }}
		<input type="submit" name="post" value="Post It!">
    </form>


	<div class="container">
          {% for statuses in statusList %}
			{% csrf_token %}
				<h3> {{ statuses.name }} </h3>
				<p> {{ statuses.status }} </p>
				<br>
			{% endfor %}
      </div>


    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>